### ISSUE TITLE
Any plans to add postgresql support?

### ISSUE THREAD

**Issue by Ak4zh** [casperbh96/Flask-Stripe-MySQL-Bootstrapped#2]

**Comment by casperbh96** [comment]
I have no experience with postgresql, but from what I understand, it shouldn't be different to using MySQL when using SQLAlchemy, since it would just be changing the config files.

You could just change this line in each init file:

https://github.com/casperbh96/Flask-Stripe-MySQL-Bootstrapped/blob/master/app/StripeMicroservice/setup_app/__init__.py#L13

**Comment by Ak4zh** [comment]
Yeah realised that later and now I have it running with postgresql.
It's great template I was searching something similar for long time.
